### ISSUE TITLE
Aggregator tx batches to be based on gas cost instead of tx count.

### ISSUE THREAD

**Issue by jzaki** [jzaki/aggregator#40]
MAX_AGGREGATION_SIZE currently is a tx count. Change to a gas limit, and can estimate gas like this -> https://github.com/jzaki/bls-wallet/blob/main/scripts/3_measure_gas.ts#L61

**Comment by voltrevo** [comment]
Canceled for now due to the slowness of `estimateGas`.

Branch: https://github.com/jzaki/aggregator/tree/agg-40-limit-txs-by-gas.
